### ISSUE TITLE
nmi_vaulted_customer.card_type column missing after v1.0.8 upgrade – causes checkout crash

### ISSUE THREAD

**Issue by eelnar-ba** [solution25com/nmi-payment-shopware-6-solution25#6]
**Description:**
After updating the NMI Payment Plugin for Shopware 6 to version v1.0.8, we encountered a critical bug during the checkout confirmation process.

**Error Message:**
`An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nmi_vaulted_customer.card_type' in 'field list'
`

**Preconditions and environment**
- Shopware version: 6.6.10.3

**Steps to reproduce**
1. Upgrade the plugin to v1.0.8.
2. Attempt to complete a checkout
3. Observe the HTTP 500 error on /checkout/confirm.
The error is also happening of you open the customer dashboard and head on to the "Saved Cards" section
![Image](https://github.com/user-attachments/assets/d5fad6ad-dbc6-4a2b-9041-0d7847e48ea3)

**Expected result**
The customer should be able to place an order successfully without any issues.

**Actual result**
The customer is unable to place an order due to the errors below.
![Image](https://github.com/user-attachments/assets/237afcf4-7398-4423-bac9-ea16eb8f241b)

**Additional information**
The error also occurs in the customer dashboard area when you click the "Saved Cards" item.
![Image](https://github.com/user-attachments/assets/264f9644-4dbd-47d0-9818-4cbe4c0a56a7)

**Comment by solution-25** [comment]
Hi @eelnar-ba ,
Thank you for reporting this issue.

To help us better understand and support you, could you please let us know how the plugin was installed or updated? 

Once we have this information, we can provide the proper guidance to ensure migrations run correctly and resolve the issue.

UPD:
After testing the plugin in various scenarios, one potential cause stood out:
If the plugin was installed or updated by manually uploading ZIP archives for each version, and each version was placed in a separate folder instead of overwriting the existing one, Shopware may not recognize the update correctly — which can cause database migrations to be skipped.

Thanks again!
The Solution25 Team

**Comment by eelnar-ba** [comment]
Hello @solution-25,

The plugin was installed via composer and it was updated via composer as well.

That's all.

Regards,
Earl

**Comment by solution-25** [comment]
Hello @eelnar-ba Earl
Thanks a lot for the clarification.

We’re currently performing a detailed review based on the Composer installation/update flow you mentioned and will get back to you shortly with an update.

Best regards,
The Solution25 Team

**Comment by solution-25** [comment]
Hi @eelnar-ba Earl,

We created a new migration adding the column ‘card_type’.
The issue is fixed in the new release version - [v1.0.9](https://github.com/solution25com/nmi-payment-shopware-6-solution25/releases/tag/v1.0.9 )

Please let us know if you have any questions.

Best regards,
The Solution25 Team

**Comment by eelnar-ba** [comment]
Hello @solution-25,

Got it Thanks!

I'll test it from my end to confirm.

Will update you guys again.

Regards,
Earl

**Comment by solution-25** [comment]
Hello Earl @eelnar-ba ,
Please let us know if we can close this issue.

Thanks!

Best regards,
The Solution25 Team

**Comment by eelnar-ba** [comment]
Hello @solution-25 ,

Yes, you can go ahead and close this issue.

Will just open another issue if ever we encounter any errors in the future.

Regards,
Earl

**Comment by eelnar-ba** [comment]
Hello @solution-25 ,

The issue still occurs after updating to the latest version 1.0.9

Regards,
Earl

**Comment by solution-25** [comment]
Hello @eelnar-ba  Earl,
Thank you for the update.
We’ll double-check the issue on our end and work on resolving it as soon as possible.
We’ll keep you posted!

Best regards,
The Solution25 Team

**Comment by solution-25** [comment]
Hi Earl @eelnar-ba ,

We’ve tested the plugin locally by installing it via Composer and checking versions 1.0.6, 1.0.7, 1.0.8, and 1.0.9.
The error you reported occurs in versions 1.0.7 and 1.0.8, but in version 1.0.9, everything works correctly.

Could you please confirm that you've followed these steps?

1. Update the plugin to version 1.0.9 using:
composer require solution25/nmi-payment:1.0.9

2. Run:
bin/console plugin:refresh
→ Make sure the plugin shows version 1.0.9

3. Update the plugin:
bin/console plugin:update NMIPayment

4. Then run:
bin/console theme:compile
bin/console cache:clear
bin/build-administration.sh

Please let us know if the issue persists after this.

Best regards,
The Solution25 Team

**Comment by eelnar-ba** [comment]
Hello @solution-25,

Yes, those are the steps we took.

Thanks,
Earl

**Comment by eelnar-ba** [comment]
Hello @solution-25,

All good now, thanks again for your help.

Regards,
Earl
